version: "3.8"

services:
  app:
    build: .
    container_name: devops-practical
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: development    # 👈 Always force development locally
      MONGO_URI: mongodb://mongo:27017/devopsdb
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped

  mongo:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data: